import { createHash } from "node:crypto";
import type { ConditionPack } from "./schema";

/**
 * Condition packs reach the database through migrations, one per pack
 * version. Each migration carries a marker with the pack's fingerprint, so
 * the build fails if a pack changes without a new version and a new
 * migration.
 */

/** Names shown to owners. A condition gets one here when its first pack is written. */
export const CONDITION_NAMES: Record<string, string> = {
  addisons: "Addison's disease",
};

export function packFingerprint(pack: unknown): string {
  return createHash("sha256").update(JSON.stringify(pack)).digest("hex");
}

export function packMarker(pack: Pick<ConditionPack, "condition" | "version">, fingerprint: string): string {
  return `-- pack ${pack.condition} ${pack.version} sha256=${fingerprint}`;
}

const sqlText = (s: string) => `'${s.replace(/'/g, "''")}'`;

export function packSeedSql(pack: ConditionPack): string {
  const name = CONDITION_NAMES[pack.condition];
  if (!name) throw new Error(`Add a name for ${pack.condition} to CONDITION_NAMES`);
  const json = JSON.stringify(pack);
  if (json.includes("$pack$")) throw new Error("The pack contains the SQL quote marker $pack$");
  const sources = JSON.stringify([...new Set(pack.medicines.flatMap((m) => m.citations.map((c) => c.sourceId)))]);
  const status = pack.status === "published" ? "live" : "draft";

  return [
    packMarker(pack, packFingerprint(pack)),
    `-- Generated by npm run pack:migration from packs/${pack.condition}.pack.json. Do not edit by hand.`,
    "",
    `insert into public.conditions (key, name, status)`,
    `values (${sqlText(pack.condition)}, ${sqlText(name)}, ${sqlText(status)})`,
    `on conflict (key) do update set name = excluded.name, status = excluded.status;`,
    "",
    `insert into public.condition_packs (condition_key, version, pack_json, reviewed_by, reviewed_on, sources)`,
    `values (`,
    `  ${sqlText(pack.condition)},`,
    `  ${sqlText(pack.version)},`,
    `  $pack$${json}$pack$::jsonb,`,
    `  ${pack.attestation ? sqlText(pack.attestation.vetName) : "null"},`,
    `  ${pack.attestation ? sqlText(pack.attestation.attestedOn) : "null"},`,
    `  ${sqlText(sources)}::jsonb`,
    `);`,
    "",
  ].join("\n");
}

export type SeedIssue = { message: string };

/** Checks that some migration seeds exactly this pack version. */
export function checkPackSeeded(pack: ConditionPack, migrations: { name: string; sql: string }[]): SeedIssue[] {
  const expected = packMarker(pack, packFingerprint(pack));
  const prefix = `-- pack ${pack.condition} ${pack.version} `;
  const seeds = migrations.filter((m) => m.sql.split("\n").some((line) => line.startsWith(prefix)));
  if (seeds.some((m) => m.sql.split("\n").includes(expected))) return [];
  if (seeds.length > 0) {
    return [{ message: `${pack.condition} ${pack.version} changed after ${seeds[0].name} seeded it. Bump the version and run npm run pack:migration.` }];
  }
  return [{ message: `No migration seeds ${pack.condition} ${pack.version}. Run npm run pack:migration -- packs/${pack.condition}.pack.json.` }];
}
